// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtk2j2_-pCu9PMf1hbowx3GM2WAjxwMN8',
    appId: '1:688157230335:web:d366c5260c8782267438ca',
    messagingSenderId: '688157230335',
    projectId: 'super-c80b2',
    authDomain: 'super-c80b2.firebaseapp.com',
    storageBucket: 'super-c80b2.firebasestorage.app',
    measurementId: 'G-CFYFVFWWEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUuNM33sjQwBatrAm3595EKTe-yIDk8os',
    appId: '1:688157230335:android:edcf076b818c65687438ca',
    messagingSenderId: '688157230335',
    projectId: 'super-c80b2',
    storageBucket: 'super-c80b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ZG25dxxu0uO9FS5TPWlQrWR6wPUyn18',
    appId: '1:688157230335:ios:4fbaf35ce8a292037438ca',
    messagingSenderId: '688157230335',
    projectId: 'super-c80b2',
    storageBucket: 'super-c80b2.firebasestorage.app',
    iosBundleId: 'com.example.foodMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ZG25dxxu0uO9FS5TPWlQrWR6wPUyn18',
    appId: '1:688157230335:ios:4fbaf35ce8a292037438ca',
    messagingSenderId: '688157230335',
    projectId: 'super-c80b2',
    storageBucket: 'super-c80b2.firebasestorage.app',
    iosBundleId: 'com.example.foodMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtk2j2_-pCu9PMf1hbowx3GM2WAjxwMN8',
    appId: '1:688157230335:web:7b42f14fc71b01cb7438ca',
    messagingSenderId: '688157230335',
    projectId: 'super-c80b2',
    authDomain: 'super-c80b2.firebaseapp.com',
    storageBucket: 'super-c80b2.firebasestorage.app',
    measurementId: 'G-CE8P5DRZJQ',
  );
}
